name: Deploy Dev

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Construir com Maven
        run: ./mvnw clean package

      - name: Fazer login no Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Construir imagem Docker
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/app-praticar:latest .
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/app-praticar:latest ${{ secrets.DOCKERHUB_USERNAME }}/app-praticar:${{ github.sha }}

      - name: Publicar imagem Docker
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-praticar:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/app-praticar:${{ github.sha }}